# Generated by Django 4.2.30 on 2026-05-01 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_add_initial_channels'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='presentation',
            field=models.CharField(default='Vlog', max_length=255),
        ),
    ]
