# Generated by Django 4.2.30 on 2026-05-04 01:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_video_presentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedrule',
            name='max_educational',
            field=models.PositiveSmallIntegerField(blank=False, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='feedrule',
            name='max_energy',
            field=models.PositiveSmallIntegerField(blank=False, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='feedrule',
            name='min_educational',
            field=models.PositiveSmallIntegerField(blank=False, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='feedrule',
            name='min_energy',
            field=models.PositiveSmallIntegerField(blank=False, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='feedrule',
            name='category_tag',
            field=models.CharField(null=True, blank=False, max_length=255),
        ),
    ]
