# Generated by Django 4.2.30 on 2026-04-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_add_initial_channels'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='energy',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
